"""fts_and_pg_trgm

Revision ID: 2f222cc59632
Revises: 5a1e0d7c9f12
Create Date: 2026-05-05 23:42:27.320307

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2f222cc59632'
down_revision: Union[str, Sequence[str], None] = '5a1e0d7c9f12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute('CREATE EXTENSION IF NOT EXISTS unaccent;')
    op.execute('CREATE EXTENSION IF NOT EXISTS pg_trgm;')
    op.execute("CREATE OR REPLACE FUNCTION public.immutable_unaccent(text) RETURNS text AS 'SELECT public.unaccent($1)' LANGUAGE sql IMMUTABLE;")
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('research_projects', sa.Column('search_vector', postgresql.TSVECTOR(), sa.Computed("to_tsvector('simple', public.immutable_unaccent(coalesce(title, '')) || ' ' || public.immutable_unaccent(coalesce(author, '')))", persisted=True), nullable=True))
    op.drop_index(op.f('ix_research_projects_author_normalized'), table_name='research_projects')
    op.drop_index(op.f('ix_research_projects_title_normalized'), table_name='research_projects')
    op.create_index('ix_research_projects_search_vector', 'research_projects', ['search_vector'], unique=False, postgresql_using='gin')
    op.drop_column('research_projects', 'author_normalized')
    op.drop_column('research_projects', 'title_normalized')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('research_projects', sa.Column('title_normalized', sa.VARCHAR(), nullable=True))
    op.add_column('research_projects', sa.Column('author_normalized', sa.VARCHAR(), nullable=True))
    op.drop_index('ix_research_projects_search_vector', table_name='research_projects', postgresql_using='gin')
    op.create_index(op.f('ix_research_projects_title_normalized'), 'research_projects', ['title_normalized'], unique=False)
    op.create_index(op.f('ix_research_projects_author_normalized'), 'research_projects', ['author_normalized'], unique=False)
    op.drop_column('research_projects', 'search_vector')
    # ### end Alembic commands ###
